### ISSUE TITLE
NaN loss at the beginning of the training

### ISSUE THREAD

**Issue by ColinQiyangLi** [y0ast/Glow-PyTorch#1]
When I start launching training with `python train.py --download`, it seems to give nan loss behaviour (a snapshoot of the terminal output as follows) consistent on this seed (7314). 
```
Using seed: 7314
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to data/CIFAR10/cifar-10-python.tar.gz
170500096it [00:08, 20744734.07it/s]                                            
Files already downloaded and verified
Epoch [1/250]: [18/781]   2%|▍                    , total_loss=nan [00:10<08:12]
```

Restarting the training with different seeds resolved the issue for me but I figured it would still be something worth to bring up :)

**Comment by y0ast** [comment]
Hey, you're right, that can sometimes happen. I'll implement the warmup strategy that Dhariwal mentions here: https://github.com/openai/glow/issues/37#issuecomment-410019221

Hopefully I can do that next week, until then just rerun and usually it works :)

**Comment by ColinQiyangLi** [comment]
@y0ast Thank you!
