### ISSUE TITLE
get_one_hot_encode() is missing.

### ISSUE THREAD

**Issue by tzyll** [y0ast/Glow-PyTorch#10]
https://github.com/y0ast/Glow-PyTorch/blob/181daaffcd0f3561f08c32d5b3846874bcc0481a/datasets.py#L76

**Comment by tzyll** [comment]
Using `one_hot_encode = lambda target: F.one_hot(torch.tensor(target), num_classes)` like get_CIFAR10 is ok.

**Comment by y0ast** [comment]
Thanks I missed that! Should be fixed now.
