### ISSUE TITLE
Error in sampling

### ISSUE THREAD

**Issue by ManushB** [y0ast/Glow-PyTorch#11]
Hi, 

I am trying to run the Sample_from_glow notebook. I receive the following error
```
File "model.py", line 217, in prior
    h += yp.view(data.shape[0], channels, 1, 1)
AttributeError: 'NoneType' object has no attribute 'shape'
```
The error arises because the notebook does not pass any z and the code in prior function expects it when y_conition is set to True.

Do we actually need z value for sampling?

**Comment by y0ast** [comment]
That was a bug on my side! It should be fixed now.

You do not need to pass z, it'll be generated from the prior.
