### ISSUE TITLE
mGPU Support

### ISSUE THREAD

**Issue by LeeDoYup** [y0ast/Glow-PyTorch#13]
When i add some code of nn.DataParallel,
i meet some errors in module.py,
the codes expect the values to be computed in the same device.

https://github.com/y0ast/Glow-PyTorch/blob/6f71c1def9c8776d2be194ba819177e7db431404/modules.py#L355

Is there any strategy or idea to uses multiple GPUs?

**Comment by xunmeibuyue** [comment]
I have added multi gpu support: https://github.com/y0ast/Glow-PyTorch/pull/25#issue-1305629474
