### ISSUE TITLE
Combining checkerboard masking with GLOW

### ISSUE THREAD

**Issue by A-Vzer** [y0ast/Glow-PyTorch#15]
Hello,

I have not yet seen code where GLOW is combined with checkerboard masking. It is always done on RealNVP. I am trying to do this however I am getting odd loss values (going from positive to negative, or extremely large). This should be possible to achieve right ?

**Comment by y0ast** [comment]
The glow paper (section 3.3) talks about it. They don't say why they don't do it, but I presume it didn't help or made things unstable. Glow is fairly unstable to train, so I am not surprised that it's difficult to get to work, but yeah it should be possible to do in principle!
