### ISSUE TITLE
Additive > Affine Coupling Layer in Terms of Generative Sampling

### ISSUE THREAD

**Issue by GloryyrolG** [y0ast/Glow-PyTorch#19]
Hi, 

This question may not be related to the code repo itself. But I saw you mention several times like,

> 1. "Note this pretrained model was created using the `affine` coupling layer, so it does not work well for generative sampling (see qualitative vs quantitative models in the Glow paper)." [ref](https://github.com/y0ast/Glow-PyTorch#glow)
>
> 2. "This works best with a model trained using the `additive` coupling layer." [ref](https://github.com/y0ast/Glow-PyTorch#evaluate)

I referred to the [original Glow paper](https://arxiv.org/pdf/1807.03039.pdf) but still did not figure it out. What do you mean by it?

Thanks.

**Comment by y0ast** [comment]
In Appendix C of the paper, there are two tables with hyper parameters: affine for quantitative (i.e. results that focus on the NLL), and additive for qualitative (i.e. results that focus on generating nice looking images).

The affine model is not invertible in a stable way, so it cannot generate nice looking images, however it does have a better NLL.
