### ISSUE TITLE
What is the reference for using this trainable log scaling factor?

### ISSUE THREAD

**Issue by uzman-anwar** [y0ast/Glow-PyTorch#24]
In the Conv2dZeros layer, we have a trainable parameter that learns gain over channels. I have failed to find any discussion on this in the Glow paper. Will appreciate any pointers on the origin of this or a simple explanation of why it helps.

https://github.com/y0ast/Glow-PyTorch/blob/91cd0b89033d256100656d587f4e595551c31235/modules.py#L244

**Comment by y0ast** [comment]
`self.logscale_factor` is not trainable:
https://github.com/y0ast/Glow-PyTorch/blob/master/modules.py#L239

`self.logs` is trainable, like in the original implementation:
https://github.com/openai/glow/blob/master/tfops.py#L311-L312

Unfortunately many details of training Glow are not in the paper, however they should all be in the OpenAI repo.
