### ISSUE TITLE
Learnable Prior?

### ISSUE THREAD

**Issue by XavierXiao** [y0ast/Glow-PyTorch#6]
I notice that in your default setting, learn_top=True, which means you use learnable prior. However, in the paper, in appendix A.1, the author said that they use prior with zero mean and unit variance for all experiments. Moreover, I want to make sure that if you use the same network structure as in the paper?

Another issue is, I find that when you sample from the flow, you only need to sample a 48x4x4 dimensional noise from the prior, which is 1/4 of the full dimension. However, if I understand correctly, in Glow, the dimensions that are discraded after splits are treated as noise dimensions, and we need to sample a full dimensional noise in order to generate samples. Could you please explain it?

**Comment by y0ast** [comment]
1. In the original code of the paper `--learn_top` is turned on for all experiments: https://github.com/openai/glow

2. We also sample the other 3/4 dimensions at each split2d layer in reverse mode: https://github.com/y0ast/Glow-PyTorch/blob/dda8e6762bb025d27f1bb70655bc4dc86f8d619f/modules.py#L273

I hope this answers your questions :)
