### ISSUE TITLE
Architecture from "Do deep..." paper

### ISSUE THREAD

**Issue by rsaite** [y0ast/Glow-PyTorch#8]
Hi @y0ast ,
thank you for sharing your implementation!
I recently started an independent implementation to reproduce the results from the "Do deep..." paper (but for the FashionMNIST/MNIST case) where I wanted to employ the architecture that Nalisnick et al. describe instead of the architecture from the original GLOW paper. Nalisnick et al. use much fewer layers per stage and highway networks for the coupling blocks (instead of regular convolutional networks), resulting in a smaller model that still gives good results and should reduce training time by quite a bit. However, I haven't been able to get this working due to instability issues (which you also seem to experience) and, when it trains, severe underfitting.

I see that you implemented the original, bigger GLOW architecture. Did you do any experiments with the smaller architecture described in "Do deep..."?

Edit for clarification: When I resorted to the bigger GLOW architecture, I was eventually able to train the model :man_shrugging:

**Comment by y0ast** [comment]
Hey, thanks for your interest!

I have not implemented the smaller Glow architectures. The VAE/PixelCNN/MAF architectures are much simpler and usually easy to train, so I would look at those.

I would not be surprised if a smaller Glow does not work that well, it's quite finicky!
